Repository devmeet-community/hacktoberfest-starter-project, pull requests merged in 2023-10, with the labels that each got.

#2 Completed the given task
  CONTRIBUTING.md
  profile/sijin-raj.md
Labels: good first issue, hacktoberfest

#3 done all steps for contribution
  CONTRIBUTING.md
  profile/Om_Patel.md
Labels: hacktoberfest, hacktoberfest-accepted

#4 completed the task 1
  CONTRIBUTING.md
Labels: hacktoberfest

#5 My Profile Contribution Added Successfully
  CONTRIBUTING.md
  profile/Ratikanta_rout.md
Labels: hacktoberfest, hacktoberfest-accepted
